### ISSUE TITLE
Allow to take input from stdin?

### ISSUE THREAD

**Issue by emmanueltouzery** [acj/krapslog-rs#1]
This looks really nice! I haven't tried it yet, but maybe just an idea.. it would be nice to allow to take input from stdin:
* More powerful filters than the ones you support, through grep
* Ability to process gzipped logfiles, though zcat and pipes

**Comment by acj** [comment]
Thanks for the kind words and suggestion. It's not documented (will fix), but you can pass input through stdin in the current release:

```
$ grep "\.jpg" sample.log | krapslog
▂▁▂▁▂▁▂▂▂▁▃▁▁▁▁▁▁▁▁▁▁▁▂▂▁▁▂▃▂▂▃▁▂▁▂▂▂▂▁▂▁▂▄▂▂▂▂▂▂▂▃▂▂▂▂▄▃▃▄▃▃▃▃▄▄▄▄▄▃▄▄▅▄▃▄▄▅▅▅▅▆▅▆▇▆█▆▇▆█▆▅▅▅▅▅▆▆▅▆█▁
```
