### ISSUE TITLE
Monitoring Of The Log's Other Information As The Dependent Variable

### ISSUE THREAD

**Issue by MikeTheSapien** [acj/krapslog-rs#5]
I have a very simple `logger` crate which outputs the following to a log file:
```
(type:"Logger",status:Fail,timestamp:"2022-04-10 19:00:06.688096500 +08:00",module:Some("middleware"),file:None,line:Some(293),title:"Insert/Update",message:"UserAuthentication(\"Unauthorized User\")",app_version:"1.0.3")
(type:"Logger",status:Success,timestamp:"2022-04-10 19:00:06.882441700 +08:00",module:Some("middleware"),file:None,line:Some(236),title:"Logging-in",message:"",app_version:"1.0.3")
```
The format is the output of using [RON](https://docs.rs/ron/0.7.0/ron/)
The following is the `logger` crate's `Cargo.toml`
```
[dependencies]
ron = "0.7.0"
chrono = "0.4.19"
serde = "1.0.136"
```

Would it be possible to monitor the occurrence of a particular substring in relation to the time it was logged?
On the example snippet of the logs above, would it be possible to count the occurrences of `module:Some("middleware")` in a given period? Or perhaps occurrences of `middleware` and `status:Success`?

A bit formal, I think: *f(x, y)*, *f* is a function where *x* is the date from which a log is entered/written to a file, and *y* is the substring that would match that particular entry.

**Comment by acj** [comment]
Hi there. Yes, you can monitor occurrences of strings by preprocessing the log file with grep and then piping the result into krapslog. If you want to graph occurrences of "middleware" in your log file, this should work:

```
grep "middleware" some-file.log | krapslog --format "%Y-%m-%d %H:%M:%S%.f"
```

The `--format` argument is needed because your timestamps are in a different format than what krapslog looks for by default. (More [here](https://github.com/acj/krapslog-rs#custom-date-formats).)

**Comment by MikeTheSapien** [comment]
Initially I felt proud for thinking of a potential feature, and excited to work on it with your guidance, but now I feel stupid 😅 
Of course you can use `grep`! You made the obvious, obvious.

Thanks for the response!
