### ISSUE TITLE
multi-line sparkline

### ISSUE THREAD

**Issue by hitenkoku** [acj/krapslog-rs#6]
This looks really nice! I want to check the following ex. multi-row sparklines.
I suggest to add height argument to function of print sparklines.

ex.

- now krapslog-rs output (one line smart output. easy to copy)
```
▂▁▂█
```

- multi-line output (multi-line output.easy to check details)

```
   *
   *
* **
****
```

**Comment by acj** [comment]
Thank you! That's a good idea for applications that need more resolution. Are you interested in a different display character (like `*`) as well, or just multi-line support for the current character set?

I won't have time to work on this for a while, but I would be happy to review a PR that implements it.

**Comment by hitenkoku** [comment]
Thank you for your comment.

> Are you interested in a different display character (like *) as well, or just multi-line support for the current character set?

I am interested in both.  I want to prefer the latter more than the former.

> I won't have time to work on this for a while, but I would be happy to review a PR that implements it.

Ok, I will try it.
